app/Check/CertificateCheck.php
app/Check/ChecksRepository.php
app/Check/Commands/Publish/CertificateChecksCommand.php
app/Check/Consumers/CertificateCheck.php
app/Check/ICheck.php
app/DashBoard/Controls/AddEditCheck/CertificateCheckProcessor.php
app/DashBoard/Controls/AddEditCheck/Factory.php
app/DashBoard/Controls/Check/Control.latte
app/DashBoard/Presenters/ProjectPresenter.php
app/config/config.neon
migrations/structures/2016-12-28-142800-certificate.sql

#3 Přidání kontroly na zjištění platnosti certifikátu

---

app/Check/ChecksRepository.php
app/Check/Commands/Publish/FeedChecksCommand.php
app/Check/Consumers/FeedCheck.php
app/Check/FeedCheck.php
app/Check/ICheck.php
app/DashBoard/Controls/AddEditCheck/Factory.php
app/DashBoard/Controls/AddEditCheck/FeedCheckProcessor.php
app/DashBoard/Controls/Check/Control.latte
app/DashBoard/Presenters/ProjectPresenter.php
app/config/config.neon
migrations/structures/2016-12-28-144452-feed-check.sql

#5 Přidání kontroly na existenci feedu

---

README.md
app/Check/ChecksRepository.php
app/Check/Commands/Publish/RabbitConsumerChecksCommand.php
app/Check/Consumers/RabbitConsumerCheck.php
app/Check/ICheck.php
app/Check/RabbitConsumerCheck.php
app/DashBoard/Controls/AddEditCheck/Factory.php
app/DashBoard/Controls/AddEditCheck/RabbitConsumerCheckProcessor.php
app/DashBoard/Controls/Check/Control.latte
app/DashBoard/Presenters/ProjectPresenter.php
app/config/config.neon
migrations/structures/2016-12-28-234567-rabbit-consumer.sql
remote/rabbitConsumer.php

#6 Přidání kontroly na minimální počet consumerů fronty

---

app/Check/Consumers/AliveCheck.php

27 Upravit chování odezvy url adresy

---

app/Check/Consumers/AliveCheck.php
app/Check/Consumers/Check.php
app/Check/Consumers/RabbitConsumerCheck.php

Všechny kontroly mají možnost opakované kontroly

---

app/DashBoard/Controls/Check/Control.latte
app/DashBoard/Controls/Check/Control.php
app/DashBoard/Presenters/templates/@layout.latte
www/js/main.js
www/js/nette.ajax.js

Issue #25 
- Nyní se se při zastavení/spuštění či obnově kontroly používají ajaxové requesty a překresluje se pouze danný box.

Napojit AJAXový refresh na kontroly

---

app/Check/Commands/SlackCheckStatusesCommand.php
app/DashBoard/Controls/Maintenance/Control.latte
app/DashBoard/Controls/Maintenance/Control.php
app/DashBoard/Controls/Maintenance/IFactory.php
app/DashBoard/Controls/Maintenance/IOnToggle.php
app/DashBoard/Controls/Project/Control.latte
app/DashBoard/Presenters/ProjectPresenter.php
app/DashBoard/Presenters/templates/@layout.latte
app/DashBoard/Presenters/templates/Project/default.latte
app/Project/Project.php
app/Slack/Notifier.php
app/config/config.neon
migrations/structures/2017-02-26-190100-maintenance.sql

Issue #33 
- Projekt je možné uvést do maintenance módu a zase zpět
- V režimu maintenance módu neodchází notifikace na Slack, ale projekt je v monitoringu živý, aby bylo možné sledovat jednotlivé kontroly

Přidána možnost maintenance módu projektu

---

app/Check/Commands/SlackCheckStatusesCommand.php
app/DashBoard/Presenters/ProjectPresenter.php
app/Project/Project.php
migrations/structures/2017-03-22-35-pauzovani-notifikaci.sql

- Projektu je možné v editaci vypnout notifikace do slacku v určitý čas
- Issue #35

 #35 Zapauzování alertování podle času

---

app/DashBoard/Controls/Project/Control.latte
app/DashBoard/Controls/Project/Control.php
app/DashBoard/Controls/Project/IFactory.php
app/DashBoard/Presenters/HomePagePresenter.php
app/DashBoard/Presenters/templates/HomePage/default.latte
app/Orm/Orm.php
app/Project/Project.php
app/User/User.php
app/UsersFavoriteProject/UsersFavoriteProject.php
app/UsersFavoriteProject/UsersFavoriteProjectMapper.php
app/UsersFavoriteProject/UsersFavoriteProjectRepository.php
composer.json
composer.lock
migrations/structures/2017-03-23-085700-favorite-projects.sql

- Projekt je možný přidat jako oblíbený, aby se uživateli ukazoval přednostně a ten měl vetší přehled.
- issue #23

Pořadí výpisu sledovaných webů

---

app/DashBoard/Controls/Logout/Control.latte
app/DashBoard/Controls/Maintenance/Control.latte
app/DashBoard/Presenters/ProjectPresenter.php
app/DashBoard/Presenters/templates/@layout.latte
app/DashBoard/Presenters/templates/Project/default.latte
www/js/main.js

Tlačítka projektu do záhlaví

---

app/DashBoard/Controls/Check/Control.php

Problém s mazáním kontroly dostupnosti URL

---

app/Check/Consumers/AliveCheck.php

Přidána vlastní User-Agent hlavička

---

app/DashBoard/Controls/AddEditCheck/AliveCheckProcessor.php
app/DashBoard/Controls/AddEditCheck/CertificateCheckProcessor.php
app/DashBoard/Controls/AddEditCheck/DnsCheckProcessor.php
app/DashBoard/Controls/AddEditCheck/FeedCheckProcessor.php
app/DashBoard/Forms/Controls/DomainControl.php

Kontrola domény v checku na certifikáty

---

app/DashBoard/Controls/AddEditCheck/FeedCheckProcessor.php
app/DashBoard/Forms/Bs3FormRenderer.php
app/DashBoard/Forms/Controls/TextInput.php
app/DashBoard/Forms/Factory.php
app/DashBoard/Presenters/ProjectPresenter.php

Přidán render s možností voleb textových inputů

---

app/Check/Check.php
app/Check/Commands/SlackCheckStatusesCommand.php
app/DashBoard/Controls/AddEditCheck/Control.php
app/DashBoard/Controls/Check/Control.latte
migrations/structures/2017-09-02-094000-onlyErrors.sql

Mít možnost hlásit jen chyby, ne varování

---

app/Check/Commands/SlackCheckStatusesCommand.php
app/DashBoard/Controls/EditUser/Control.php
app/DashBoard/Controls/Project/Control.latte
app/DashBoard/Controls/Project/Control.php
app/DashBoard/Controls/Project/IFactory.php
app/DashBoard/Forms/UserEditFormFactory.php
app/DashBoard/Presenters/BasePresenter.php
app/DashBoard/Presenters/HomePagePresenter.php
app/DashBoard/Presenters/ProjectPresenter.php
app/DashBoard/Presenters/UserPresenter.php
app/DashBoard/Presenters/templates/@layout.latte
app/Orm/Orm.php
app/Project/Project.php
app/User/User.php
app/UserSlackNotifications/UserSlackNotifications.php
app/UserSlackNotifications/UserSlackNotificationsMapper.php
app/UserSlackNotifications/UserSlackNotificationsRepository.php
migrations/structures/2017-09-06-163600-user-slack-notifications.sql
migrations/structures/2017-10-06-125500-notifications.sql

[WIP] Je možné pozastavit notifikace pro celý projekt

---

app/Check/ChecksRepository.php
app/Check/Commands/Publish/PublishChecksCommand.php
app/Check/Commands/Publish/RabbitQueueChecksCommand.php
app/Check/Consumers/RabbitQueueCheck.php
app/Check/ICheck.php
app/Check/RabbitQueueCheck.php
app/DashBoard/Controls/AddEditCheck/Factory.php
app/DashBoard/Controls/AddEditCheck/RabbitQueueCheckProcessor.php
app/DashBoard/Controls/Check/Control.latte
app/DashBoard/Presenters/ProjectPresenter.php
app/config/config.neon
config/supervisor.conf
migrations/structures/2017-11-03-160000-rabbitmq-messages.sql

Přidána kontrola na počet zpráv ve frontě

---

app/Check/ChecksRepository.php
app/Check/Commands/Publish/HttpStatusCodeChecksCommand.php
app/Check/Consumers/HttpStatusCodeCheck.php
app/Check/HttpStatusCodeCheck.php
app/Check/ICheck.php
app/DashBoard/Controls/AddEditCheck/Factory.php
app/DashBoard/Controls/AddEditCheck/HttpStatusCodeCheckProcessor.php
app/DashBoard/Controls/Check/Control.latte
app/DashBoard/Presenters/ProjectPresenter.php
app/config/config.neon
migrations/structures/2018-01-29-100000-http-status-code.sql

#7 Přidání kontroly na HTTP stavový kód

---

app/Check/Consumers/DnsCheck.php
app/Check/DnsCheck.php
app/DashBoard/Controls/AddEditCheck/DnsCheckProcessor.php
app/DashBoard/Controls/Check/Control.latte
migrations/structures/2018-02-22-133500-dns.sql

Kontrola DNS umí více typů

---

app/Check/Commands/SlackCheckStatusesCommand.php
app/DashBoard/Controls/AddEditCheck/Factory.php
app/DashBoard/Controls/Project/Control.php
app/DashBoard/Presenters/HomePagePresenter.php
app/DashBoard/Presenters/ProjectPresenter.php
app/DashBoard/Presenters/templates/HomePage/default.latte
app/Project/Project.php
app/Project/ProjectsMapper.php
app/Project/ProjectsRepository.php
migrations/structures/2018-06-27-090757-reference.sql

Selhání referenční kontroly ukončí hlášení do Slacku

---

app/Check/Commands/SlackCheckStatusesCommand.php
app/Check/RabbitConsumerCheck.php
app/Check/RabbitQueueCheck.php
app/DashBoard/Controls/AddEditCheck/RabbitConsumerCheckProcessor.php
app/DashBoard/Controls/AddEditCheck/RabbitQueueCheckProcessor.php
app/DashBoard/Controls/Check/Control.latte
migrations/structures/2018-07-02-100000-rabbit-admin.sql

K RabbitMQ kontrolám je možné doplnit odkaz na webovou administraci

---

app/Check/ChecksMapper.php
app/Check/ChecksRepository.php
app/Check/Commands/Publish/NumberValueChecksCommand.php
app/Check/Consumers/NumberValueCheck.php
app/Check/ICheck.php
app/Check/NumberValueCheck.php
app/DashBoard/Controls/AddEditCheck/Factory.php
app/DashBoard/Controls/AddEditCheck/NumberValueCheckProcessor.php
app/DashBoard/Controls/Check/Control.latte
app/DashBoard/Controls/ProjectButtons/Control.php
app/config/config.neon
migrations/structures/2018-07-17-103000-number-value.sql

Přidána kontrola na číselnou hodnotu

---

app/Check/Consumers/RabbitConsumerCheck.php
app/Check/Consumers/RabbitQueueCheck.php
app/Check/RabbitConsumerCheck.php
app/Check/RabbitQueueCheck.php
app/DashBoard/Controls/AddEditCheck/RabbitConsumerCheckProcessor.php
app/DashBoard/Controls/AddEditCheck/RabbitQueueCheckProcessor.php
migrations/structures/2018-10-15-133700-validate-https.sql

Kontroly RabbitMQ umí nevalidovat HTTPS certifikát

---

app/Check/ChecksRepository.php
app/Check/Commands/Publish/XpathChecksCommand.php
app/Check/Consumers/XpathCheck.php
app/Check/ICheck.php
app/Check/XpathCheck.php
app/DashBoard/Controls/AddEditCheck/Factory.php
app/DashBoard/Controls/AddEditCheck/XpathCheckProcessor.php
app/DashBoard/Controls/Check/Control.latte
app/DashBoard/Controls/ProjectButtons/Control.php
app/config/config.neon
composer.json
composer.lock
migrations/structures/2019-01-30-163000-xpath.sql

Přidána kontrola na XPath

---

app/DashBoard/Controls/AliveChart/Control.php
app/DashBoard/Controls/AliveChart/IFactory.php
app/DashBoard/Controls/Check/Control.latte
app/DashBoard/Controls/Check/Control.php
app/DashBoard/Presenters/templates/@layout.latte
app/Elasticsearch/ClientFactory.php
app/Elasticsearch/Queries/AverageTimeoutQuery.php
app/config/config.neon

Napojeny průměrné odezvy časových kontrol

---

app/Check/AliveCheck.php
app/Check/Check.php
app/Check/Commands/Publish/AliveChecksSiteMapCommand.php
app/Check/Commands/Publish/XpathChecksCommand.php
app/Check/Commands/Publish/XpathChecksSiteMapCommand.php
app/Check/Consumers/AliveCheck.php
app/Check/Consumers/XpathCheck.php
app/Check/SiteMapLoader.php
app/Check/XpathCheck.php
app/DashBoard/Controls/AddEditCheck/AliveCheckProcessor.php
app/DashBoard/Controls/AddEditCheck/XpathCheckProcessor.php
app/config/config.neon
config/crontab
config/supervisor.conf
migrations/structures/2019-03-26-123456.sql

Některé kontroly umí kontrolovat obsah sitemapy

---

app/Check/ChecksRepository.php
app/Check/Commands/Publish/ErrorsChecksCommand.php
app/Check/Consumers/ErrorsCheck.php
app/Check/ErrorsCheck.php
app/Check/ICheck.php
app/DashBoard/Controls/AddEditCheck/ErrorsCheckProcessor.php
app/DashBoard/Controls/AddEditCheck/Factory.php
app/DashBoard/Controls/Check/Control.latte
app/DashBoard/Controls/ProjectButtons/Control.php
app/config/config.neon
config/crontab
migrations/structures/2020-01-11-121555-errors-check.sql

Kontrola na chyby

---

app/DashBoard/Controls/AddEditCheck/RabbitConsumerCheckProcessor.php

Nejde zadat různý počet prvků

---

app/Router/RouterFactory.php

Odebrána stará routa na přihlášení

---

app/Check/Check.php
app/DashBoard/Controls/Check/Control.latte
app/DashBoard/Controls/EditUser/Control.php
app/DashBoard/Controls/Maintenance/Control.php
app/DashBoard/Controls/Project/Control.latte
app/DashBoard/Controls/Project/Control.php
app/DashBoard/Controls/ProjectButtons/Control.latte
app/DashBoard/Controls/Settings/Control.latte
app/DashBoard/Forms/UserEditFormData.php
app/DashBoard/Forms/UserEditFormFactory.php
app/DashBoard/Presenters/CheckPresenter.php
app/DashBoard/Presenters/ProjectPresenter.php
app/DashBoard/Presenters/UserPresenter.php
app/DashBoard/Presenters/templates/HomePage/default.latte
app/Project/Project.php
app/User/AclFactory.php
app/User/User.php
phpstan-baseline.neon

Doplněno ACL na jednotlivé dílčí resourcy

---

app/DashBoard/Controls/DataGridFactory.php
app/DashBoard/Controls/UserOnProject/Factory.php
app/DashBoard/Presenters/ProjectPresenter.php
app/DashBoard/Presenters/templates/Project/edit.latte
app/Orm/Orm.php
app/User/User.php
app/UserOnProject/UserOnProject.php
app/UserOnProject/UserOnProjectMapper.php
app/UserOnProject/UserOnProjectRepository.php
app/config/config.neon
composer.json
composer.lock
migrations/structures/2021-04-27-200000-user-on-project.sql
phpstan-baseline.neon

K projektu je možné přiřadit uživatele s různým oprávněním

---

app/DashBoard/Controls/Check/Control.php
app/DashBoard/Controls/Maintenance/Control.php
app/DashBoard/Controls/Project/Control.php
app/DashBoard/Presenters/HomePagePresenter.php
app/Project/ProjectsMapper.php
app/Project/ProjectsRepository.php
app/User/AclFactory.php
app/config/config.neon
phpstan-baseline.neon

Napojení nastaveného oprávnění uživatelů na ACL

---

app/DashBoard/Controls/ProjectChecks/Control.php
app/DashBoard/Controls/SubProjects/Control.php
app/Router/RouterFactory.php
phpstan-baseline.neon

Doplněno ACL na podprojekty

---

app/DashBoard/Controls/UserOnProject/Factory.php

Editace předvyplňuje hodnoty

---

app/DashBoard/Controls/Project/Control.php
phpstan-baseline.neon

Do grafu checků se načítá jen z povolených projektů

---

app/Check/Commands/SlackCheckStatusesCommand.php
app/DashBoard/Controls/SlackIntegrationOnProject/Factory.php
app/DashBoard/Presenters/ProjectPresenter.php
app/DashBoard/Presenters/templates/Project/edit.latte
app/Orm/Orm.php
app/Project/Project.php
app/Slack/Integration.php
app/Slack/IntegrationMapper.php
app/Slack/IntegrationRepository.php
app/config/config.neon
migrations/structures/2021-04-29-174200-slack.sql
phpstan-baseline.neon

Integrace na Slack je v databázi a přiřazuje se k projektu

---

app/DashBoard/Controls/UserOnProject/Factory.php
phpstan-baseline.neon

Je vyžadováno aspoň jedno oprávnění

---

app/DashBoard/Controls/UserOnProject/Factory.php

ID musí být stringové

---

app/Check/Commands/SlackCheckStatusesCommand.php
app/DashBoard/Controls/Maintenance/Control.php
app/DashBoard/Controls/SlackIntegrationOnProject/Factory.php
app/Project/Project.php
app/Slack/Integration.php
migrations/structures/2021-07-01-155007-slack-integration-channel.sql
phpstan-baseline.neon

Slack Integrace – přidana možnost editovat konkrétní kanál na Slacku

---

.gitignore
Makefile
app/DashBoard/Presenters/LoginPresenter.php
app/DashBoard/Presenters/templates/Login/default.latte
app/Github/GitHubLogin.php
app/config/config.neon
docker-compose.yml

- lze vypnout v konfigurace parameters.github.allow
- výchozí stav je povolen tedy TRUE

Přihlášení přes GH lze vypnout v konfiguraci

---

app/DashBoard/Presenters/HomePagePresenter.php
app/DashBoard/Presenters/templates/HomePage/default.latte
app/Project/ProjectsMapper.php
app/Project/ProjectsRepository.php

- v případě, že uživatel není admin a nemá přiřazen projekt se chybně sestavilo SQL a došlo k erroru v dashboardu
- nyní opraveno a přidána hláška, která uživatele navede, jak má dále pokračovat

Oprava chyby na dashboardu

---

app/Check/RabbitQueueCheck.php

#174 Kontrola počtu zpráv při záporné hodnotě zpráv hlásí chybu

---

app/Check/Consumers/HttpStatusCodeCheck.php
app/Check/Consumers/RabbitConsumerCheck.php
app/Check/Consumers/RabbitQueueCheck.php

- #181  Log the start of the check to better debug

181  Log the start of the check to better debug

---

app/Check/Consumers/CertificateCheck.php
app/Check/Consumers/HttpStatusCodeCheck.php

179 Added missing guzzle request timeout option 

---

app/Check/Consumers/AliveCheck.php
app/Check/Consumers/ErrorsCheck.php
app/Check/Consumers/XpathCheck.php

- #173 catch ConnectExceptionLog where missing

#173 - catch ConnectExceptionLog where missing
